[workspace]
name = "cudabook"
version = "0.1.0"
description = "Programming Massively Parallel Programs book notes"
authors = ["igodlab"]
channels = [
    "https://conda.modular.com/max-nightly/",
    "conda-forge",
]
platforms = ["linux-64"]

# Core dependencies
[dependencies]
modular = "*"
jupyterlab = ">=4.4.10, <5.0"
python = ">=3.12, <4.0"
numpy = ">=2.3, <3.0"
pandas = ">=2.3.3, <3.0"
plotly = ">=6.3.1, <7.0"


[pypi-dependencies]
catppuccin-jupyterlab = ">=0.2.4, <0.3"

# Useful tasks
[tasks]
jupyter_lab = "jupyter lab"
mojo = "mojo"
modular = "modular"

# Check Mojo installation
[tasks.check]
cmd = "mojo --version && modular --version"

# Start Jupyter with Mojo kernel (if available)
[tasks.notebook]
cmd = "jupyter lab --allow-root"
